import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeContextProvider } from "@/context/ThemeContext";
import ThemeProvider from "@/provider/ThemeProvider";
import Footer from "@/app/component/Footer/Footer";
import NavBar from "@/app/component/NavBar/NavBar";
import AuthProvider from "@/provider/AuthProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>

          <ThemeContextProvider>
            <ThemeProvider>
              <div className="min-h-screen ">
                <div className="max-w-[95rem] mx-auto ">
                  <NavBar className=' py-2 p-10' />
                  {children}
                  <Footer className=' py-10 px-40 ' />
                </div>
              </div>
            </ThemeProvider>
          </ThemeContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
